/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot.glb 
Author: gornostai (https://sketchfab.com/gornostai)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-love-death-and-robots-c54c32bed0364e11aeefd380950ab361
Title: Robot (Love, Death and Robots)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Robot(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/robot.glb");

  // Rotate Continuously
  useFrame((state, delta) => {
    if (group.current) {
      group.current.rotation.y += delta * 0.5; // speed
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder_Material001_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cylinder_Material002_0.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes["Cylinder_��������������_0"].geometry}
          material={materials.material}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder002_Material001_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cylinder002_Material003_0.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder005_Material002_0.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes["Cylinder005_��������������_0"].geometry}
          material={materials.material}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder006_Material002_0.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes["Cylinder006_��������������_0"].geometry}
          material={materials.material}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder007_Material001_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cylinder007_Material003_0.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder008_Material001_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cylinder008_Material003_0.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder009_Material002_0.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes["Cylinder009_��������������_0"].geometry}
          material={materials.material}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder023_Material001_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes["Cylinder023_��������������_0"].geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Cylinder023_Material003_0.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cylinder023_Material002_0.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder024_Material001_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cylinder024_Material003_0.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes["Cylinder024_��������������_0"].geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Cylinder024_Material002_0.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes["Cylinder026_��������������_0"].geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Cylinder026_Material002_0.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder027_Material002_0.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes["Cylinder027_��������������_0"].geometry}
          material={materials.material}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes["Cylinder028_��������������_0"].geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Cylinder028_Material002_0.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder030_Material002_0.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes["Cylinder030_��������������_0"].geometry}
          material={materials.material}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder032_Material003_0.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes["Cylinder032_��������������_0"].geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Cylinder032_Material002_0.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder034_Material002_0.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes["Cylinder034_��������������_0"].geometry}
          material={materials.material}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder035_Material002_0.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes["Cylinder035_��������������_0"].geometry}
          material={materials.material}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder036_Material001_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cylinder036_Material003_0.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder037_Material001_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cylinder037_Material003_0.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder038_Material002_0.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes["Cylinder038_��������������_0"].geometry}
          material={materials.material}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder052_Material001_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes["Cylinder052_��������������_0"].geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Cylinder052_Material003_0.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cylinder052_Material002_0.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder053_Material001_0.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cylinder053_Material003_0.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes["Cylinder053_��������������_0"].geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Cylinder053_Material002_0.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes["Cylinder055_��������������_0"].geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Cylinder055_Material002_0.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder056_Material002_0.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes["Cylinder056_��������������_0"].geometry}
          material={materials.material}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes["Cylinder057_��������������_0"].geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Cylinder057_Material002_0.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder059_Material002_0.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes["Cylinder059_��������������_0"].geometry}
          material={materials.material}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cylinder061_Material003_0.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes["Cylinder061_��������������_0"].geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Cylinder061_Material002_0.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder001_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder003_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder004_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder010_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder011_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder012_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder013_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder014_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder015_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder016_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder017_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder018_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder019_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder020_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder021_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder022_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder025_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder029_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder031_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube_Material001_0.geometry}
        material={materials["Material.001"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube001_Material001_0.geometry}
        material={materials["Material.001"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube002_Material005_0.geometry}
        material={materials["Material.005"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder039_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder040_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder041_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder042_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder043_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder044_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder045_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder046_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder047_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder048_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder049_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder050_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes["Cylinder051_��������������_0"].geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder054_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder058_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cylinder060_Material002_0.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube003_Material001_0.geometry}
        material={materials["Material.001"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube004_Material004_0.geometry}
        material={materials["Material.004"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Circle_Material005_0.geometry}
        material={materials["Material.005"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("./models/robot.glb");
